version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL="postgresql://admin:qwerty@postgres:5432/nest_json?schema=public"
      - PORT=6754
      - SECRET=supersecret
    depends_on:
      - postgres
    ports:
      - '6754:6754'
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:16
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=nest_json
    ports:
      - '5434:5432'

volumes:
  postgres-data:
